{{- if and (not .Values.mariadb.enabled) (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailpiler.databaseSecretName" . }}
  labels:
    {{- include "mailpiler.labels" . | nindent 4 }}
    app.kubernetes.io/component: mailpiler
type: Opaque
data:
  {{ .Values.database.passwordKey }}: {{ required "database.password is required when mariadb.enabled is false and database.existingSecret is not set" .Values.database.password | b64enc | quote }}
{{- end }}