apiVersion: v2
name: mailpiler
description: Mailpiler is a powerful, scalable email archiving platform that helps organizations comply with regulations, reduce storage costs, and improve email management. 
type: application
version: 0.1.1
appVersion: "1.4.8"

dependencies:
  - name: mariadb
    version: 0.10.1
    repository: oci://registry-1.docker.io/cloudpirates
    condition: mariadb.enabled
  - name: memcached
    version: 0.8.2
    repository: oci://registry-1.docker.io/cloudpirates
    condition: memcached.enabled
  - name: manticoresearch
    version: 15.1.0
    repository: https://manticoresoftware.github.io/manticoresearch-helm
    condition: manticoresearch.enabled